### ISSUE TITLE
E2E Testing Spike

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#1583]
## Summary

This issue tracks the work for the E2E Testing investigation.

## Problem Definition

We want to be able to easily write automated E2E tests to verify the correctness of code in the ibc-go repo by
creating real instances of `simd` and `icad` and a relayer, performing operations and asserting conditions. 

## Proposal

Investigate existing frameworks or the work involved in writing our own solution.

## Tasks

- [x] Create a [Dockerfile for simd](https://github.com/cosmos/ibc-go/pull/1485)
- [x] Create a [Dockerfile for icad](https://github.com/cosmos/interchain-accounts-demo/pull/95)
- [x] Experiment with home grown solution. (After some experimentation, this is definitely re-inventing the wheel, a lot of this work has already been done with [this pr](https://github.com/cosmos/gaia/pull/1253) and [ibctest](https://github.com/strangelove-ventures/ibctest))
- [x] Missing from ibctest that we would need to use it to write tests:
  - [x] Support for [exposing relayer information](https://github.com/strangelove-ventures/ibctest/pull/164) (required for fee middleware tests)
  - [x] [Enable broadcasting of transactions](https://github.com/strangelove-ventures/ibctest/pull/186) so that we can use go clients to sign transactions in the tests. (And not depend on docker exec to do operations)
  - [x] [Arbitrary execution of commands](https://github.com/strangelove-ventures/ibctest/pull/173) so that we can test features before they are released.
  - [x] [Fine grained control over channel creation](https://github.com/strangelove-ventures/ibctest/issues/155)
  - [x] Allow for the ability to [create users using specific mnemonics](https://github.com/strangelove-ventures/ibctest/pull/176)
  - [x] ~[Configurable ports for the docker containers](https://github.com/strangelove-ventures/ibctest/issues/177)~

- [x] Github action CI work
  - [x] Create github action to run e2e tests under "e2e" directory.
  - [x] Build images from the code of PRs, and push to ghcr registry.
  - [x] Dynamically build test matrix based on tests under the "e2e" directory. 
 

- [x] Write some example tests with the ibctest framwork based on [these scenarios](https://github.com/cosmos/ibc-go/issues/396)
  - [X] TestBasicIBCTransfer 
  - [X] TestFeeMiddlewareAsyncSingleSenderTimesOut 
  - [X] TestFeeMiddlewareAsyncSingleSender 
  - [X] TestFeeMiddlewareAsyncMultipleSenders  
  - [x] TestFeeMiddlewareSyncSingleSender depends on [Exposing private keys of test users](https://github.com/strangelove-ventures/ibctest/issues/172)  and  [Configurable ports for the docker containers](https://github.com/strangelove-ventures/ibctest/issues/177)

The work is being done [here](https://github.com/cosmos/ibc-go/pull/1553)

### Split into issues

- [x] #1642
- [x] #1643
- [x] #1648
- [ ]  Add Test Cases
   - [x] #1652
   - [x] https://github.com/cosmos/ibc-go/issues/1686
   - [x] https://github.com/cosmos/ibc-go/issues/1685 
   - [x] https://github.com/cosmos/ibc-go/issues/1684
   - [x] #1752
 - [x] https://github.com/cosmos/ibc-go/issues/1683

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned
