### ISSUE TITLE
Channel upgrades

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#1599]
Meta issue for tracking the `ibc-go` implementation of the [ICS-004 Channel Upgrades specification](https://github.com/cosmos/ibc/blob/master/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md)

Requirements document (coming soon...)
[Project board ](https://github.com/orgs/cosmos/projects/7/views/17)

## Milestones

- [Alpha](https://github.com/cosmos/ibc-go/milestone/29)

## Implementation issues

**Note**: placeholders will be replaced as issues are added and linked to this epic. Some of the issues implemented are outdated and may not be reflected in the most up to date version of the code
 
### Store paths

The following standardised store paths should be added to `24-host`:

- https://github.com/cosmos/ibc-go/issues/1600
- https://github.com/cosmos/ibc-go/issues/1601
- https://github.com/cosmos/ibc-go/issues/1602
- https://github.com/cosmos/ibc-go/issues/1603

### State verification functions

The following state verification functions should be added to `03-connection` for verifying proofs against a counterparty lightclient:

- https://github.com/cosmos/ibc-go/issues/1608
- https://github.com/cosmos/ibc-go/issues/1609
- https://github.com/cosmos/ibc-go/issues/1610

### Upgrade handshake

- https://github.com/cosmos/ibc-go/issues/1604
- https://github.com/cosmos/ibc-go/issues/1617
    - https://github.com/cosmos/ibc-go/issues/1622
    - https://github.com/cosmos/ibc-go/issues/1618
    - https://github.com/cosmos/ibc-go/issues/1619
    - https://github.com/cosmos/ibc-go/issues/1620
    - https://github.com/cosmos/ibc-go/issues/1621

### Upgrade cancellation

- https://github.com/cosmos/ibc-go/issues/1605
- https://github.com/cosmos/ibc-go/issues/1612
- https://github.com/cosmos/ibc-go/issues/1623
- https://github.com/cosmos/ibc-go/issues/3373
- https://github.com/cosmos/ibc-go/issues/1624

### Upgrade timeout

- https://github.com/cosmos/ibc-go/issues/1606
- https://github.com/cosmos/ibc-go/issues/1625
- https://github.com/cosmos/ibc-go/issues/1626

### Query handlers

- https://github.com/cosmos/ibc-go/issues/1902
- https://github.com/cosmos/ibc-go/issues/1901

### Application callbacks

- https://github.com/cosmos/ibc-go/issues/1614
- https://github.com/cosmos/ibc-go/issues/4127
- https://github.com/cosmos/ibc-go/issues/1900

## Automated e2e tests

- #3421

## Checklist

- [ ] Internal audit(s)
- [ ] External audit(s)
- [ ] Documentation
- [ ] Swagger
- [ ] Integration with relayers:
  - [ ] Hermes
  - [ ] Rly
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
