### ISSUE TITLE
E2E Test Coverage

### ISSUE THREAD

**Issue by chatton** [cosmos/ibc-go#1607]
## Summary

This issue tracks desirable E2E tests for our existing modules and features.

#### Happy Paths
* #2021 
* #2023

#### Unhappy Paths
* #2021
* #2048

#### Happy Paths
* #1684
* #1752 
* #1652  

#### Unhappy Paths
* #1685 
* #1686 
* #1967

#### Happy Paths
* 

#### Unhappy Paths
* #1992 

#### Happy Paths
* 

#### Unhappy Paths
* 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
