### ISSUE TITLE
v4.0.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#1757]
This release main feature addition is [Fee Middleware](https://github.com/cosmos/ibc-go/issues/396).

## Milestones

[v4.0.0 milestone](https://github.com/cosmos/ibc-go/milestone/26)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] Fungible token transfers over a non-incentivised channel works with a counterparty chain running each previous major version.
- [x] Interchain Accounts over a non-incentivised channel works with a counterparty chain running each previous major version that supports ICS-27 Interchain Accounts over non-incentivised channels.

### Other testing

- Tests for migration to correct malformed denom trace information:
  - [x] Test upgrading a directly to v4.0.0 (i.e. chain had not upgraded before to any intermediate version adding support for transfers of base denoms with slashes). Steps:
    - Set up chain 1 on v3.1.0 (or any other version that added support for transfers of base denoms with slashes) with an account that has in balance tokens of a base denom that contains slashes (for example: `gamm/pool/1`).
    - Set up chain 2 on v3.0.0 (or any other version that does not have support for transfers of base denoms with slashes).
    - Transfer tokens of the base denom that contains slashes from chain 1 to chain 2.
    - Verify that denom trace information is corrupted on chain 2.
    - Upgrade chain 2 to v4.0.0.
    - Verify that denom trace information is corrected.
    - Verify that the consensus version of the transfer module has been bumped to 2 (`simd q upgrade module_versions`).
    - Verify that tokens can be transferred back to chain 1.
  - [x] Test upgrading to v4.0.0 after upgrading to an intermediate version adding support for transfers of base denoms with slashes. Steps:
    - Set up chain 1 on v3.1.0 (or any other version that added support for transfers of base denoms with slashes) with an account that has in balance tokens of a base denom that contains slashes (for example: `gamm/pool/1`).
    - Set up chain 2 on v3.0.0 (or any other version that does not have support for transfers of base denoms with slashes).
    - Transfer tokens of the base denom that contains slashes from chain 1 to chain 2.
    - Verify that denom trace information is corrupted on chain 2.
    - Upgrade chain 2 to v3.1.0.
    - Verify that denom trace information is corrected.
    - Upgrade chain 2 to v4.0.0.
    - Verify that the consensus version of the transfer module has been bumped to 2 (`simd q upgrade module_versions`).
    - Verify that tokens can be transferred back to chain 1.
  - [x] Test the migration will panic if chain has custom port ID for transfer module and denom trace information is corrupted. Steps:
    - Set up chain 1 on v3.1.0 (or any other version that added support for transfers of base denoms with slashes) with an account that has in balance tokens of a base denom that contains slashes (for example: `gamm/pool/1`).
    - Set up chain 2 on v3.1.0 with a custom port ID for transfer module in `genesis.json` (for example: `customtransfer`), but leave the [port ID constant in the transfer module](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/types/keys.go#L19) as is (i.e. `transfer`).
    - Transfer tokens of the base denom that contains slashes from chain 1 to chain 2.
    - Verify that the vouchers are minted on chain 2 with a native base denom (i.e. not an IBC denom; e.g. `customtransfer/channel-0/gamm/pool/1`).
    - Upgrade chain 2 to v4.0.0.
    - Verify that the consensus version of the transfer module is still 1.
    - Verify that the migration panics and the chain does not start.

## Migration 

[Migration from v3 to v4](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v3-to-v4.md)

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v3` to `github.com/cosmos/ibc-go/v4`.
- [x] Branch off main to create release branch in the form  of `release/v4.0.0`.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [x] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md).
- [x] Update docs site:
  - [x] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [x] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L33).
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
[v4.0.0](https://github.com/cosmos/ibc-go/releases/tag/v4.0.0) has been released.
