### ISSUE TITLE
v5.0.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#1800]
This release's main addition is the upgrade to Cosmos SDK 0.46.

## Milestones

[v5.0.0 milestone](https://github.com/cosmos/ibc-go/milestone/33)

## IBC spec compatibility

v1.0

#### Fungible token transfers

- Over a **non-incentivised** channel:
  - Successful token transfer:
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2846874526) 
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v3)](https://github.com/cosmos/ibc-go/actions/runs/2847494327)
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v2)](https://github.com/cosmos/ibc-go/actions/runs/2847505861)
    - [x] [chain A (ibc-go v4) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2846888103) 
    - [x] [chain A (ibc-go v3) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/runs/7808214404?check_suite_focus=true)
    - [x] [chain A (ibc-go v2) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2847525781) 
  - Failed token transfer (e.g. receiver address is not valid) 
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2847488509) 
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v3)](https://github.com/cosmos/ibc-go/actions/runs/2847494327) 
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v2)](https://github.com/cosmos/ibc-go/actions/runs/2847505861) 
    - [x] [chain A (ibc-go v4) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2847516743) 
    - [x] [chain A (ibc-go v3) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/runs/7808214404?check_suite_focus=true) 
    - [x] [chain A (ibc-go v2) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2847525781)
- Over an **incentivised** channel:
  - Successful token transfer:
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2838323158)
    - [x] [chain A (ibc-go v4) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2846824830)
  - Failed token transfer (e.g. receiver address is not valid) 
    - [x] [chain A (ibc-go v5) -> chain B (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2846830439)
    - [x] [chain A (ibc-go v4) -> chain B (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2846824830)

#### Interchain Accounts 

- Over a **non-incentivised** channel:
  - Successful interchain account registration AND successful bank transfer on the host (from the interchain account):
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v3)](https://github.com/cosmos/ibc-go/runs/7901882397?check_suite_focus=true)
    - [x] [controller chain (ibc-go v4) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2882039089)
    - [x] [controller chain (ibc-go v3) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2882004115)
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2882043841)
  - Successful interchain account registration BUT failed bank transfer (e.g. insufficient funds in sender) on the host (from the interchain account):
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v3)](https://github.com/cosmos/ibc-go/runs/7901882397?check_suite_focus=true)
    - [x] [controller chain (ibc-go v4) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2882039089)
    - [x] [controller chain (ibc-go v3) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2882004115)
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2882043841)
- Over an **incentivised** channel:
  - Successful interchain account registration AND successful bank transfer on the host (from the interchain account):
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v4)](https://github.com/cosmos/ibc-go/runs/7897603289?check_suite_focus=true)
    - [x] [controller chain (ibc-go v4) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/runs/7897590239?check_suite_focus=true) 
  - Successful interchain account registration BUT failed bank transfer (e.g. insufficient funds in sender) on the host (from the interchain account):
    - [x] [controller chain (ibc-go v5) / host chain (ibc-go v4)](https://github.com/cosmos/ibc-go/actions/runs/2888765757)
    - [x] [controller chain (ibc-go v4) / host chain (ibc-go v5)](https://github.com/cosmos/ibc-go/actions/runs/2888768714) 

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v4` to `github.com/cosmos/ibc-go/v5`.
- [x] Branch off main to create release branch in the form  of `release/v5.0.x`.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [x] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check migration docs.
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md).
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`.
- [x] Update docs site:
  - [x] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [x] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L33).
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by chatton** [comment]
We should add any automated tests that get added as a result of this work to #1607

**Comment by crodriguezvega** [comment]
[v5.0.0](https://github.com/cosmos/ibc-go/releases/tag/v5.0.0) is released.
