### ISSUE TITLE
Add migrations for solo machine protobuf types

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#1863]
## Summary

Todo:
- [x] add optional migrations #2800 
- [x] add automatic in-place store migrations #2819 
- [x] add genesis migrations #2824 
- [ ] remove legacy migrations
- [x] review documentation

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
remove `Allow` boolean in solo machine client state as well

**Comment by colin-axner** [comment]
I did some initial work for this since the issue lacked sufficient information to get started. https://github.com/cosmos/ibc-go/tree/colin/1863-v7-migrations

What I have done:
- reused v1 to v2 consensus version migrations and renamed them to v2 to v3
- moved localhost migration to v2 to v3 migrations and made it automatic
- moved all migrations into `02-client/migrations/v7`
- removed addition of metadata (used in v1 to v2)
- updated solomachine migration to be v2 to v3 proto definition

What's left?
- decide if we want to support genesis migrations (it's really messy), if so review the tendermint expired client migration code (I only removed the addition of the extra metadata, but it might be possible to simplify)
- fix broken tests 
- probably move localhost_test.go into store_test.go
- potentially add genesis migration test for localhost
- remove localhost client state in genesis migration (not currently happening because it is a bit tricky)

Note: It will not be possible to upgrade from stargate -> v7

**Comment by colin-axner** [comment]
Further thoughts:

Let's move tendermint expired consensus state pruning into an optional migration which chains can call directly. I like the idea of optimizations being optional and required migrations being automatic. Iterating over all clients/consensus states can actually take quite a bit of time (a year ago it took like an hour), so I think it makes sense to skip as automatic. It could also be reused during any upgrade. Only iterating over solo machine/localhost clients should be a lot faster!

Lets also add logging to the expired tendermint pruning. Might be nice to log the number of consensus states pruned. This can inform a chain whether it is worth running the migration or not since even if 2 consensus states are pruned, all consensus states will be iterated
