### ISSUE TITLE
v7.0.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#1864]
Main additions to this release are:

#### 02-client refactor

This refactor will make the development of light clients easier. The ibc-go implementation will finally align with the spec and light clients will be required to set their own client and consensus states. This will allow more flexibility for light clients to manage their own internal storage and do batch updates. See [ADR 006](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-006-02-client-refactor.md) for more information.

Follow the progress with the [beta](https://github.com/cosmos/ibc-go/milestone/25) and [RC](https://github.com/cosmos/ibc-go/milestone/27) milestones or in the [project board](https://github.com/orgs/cosmos/projects/7/views/14).

#### Upgrade SDK v0.47.x

Follow the progress with the [milestone](https://github.com/cosmos/ibc-go/milestone/36).

#### Add `authz` support to 20-transfer

See #2431 for more details.

## Milestones

[v7.0.0 milestone](https://github.com/cosmos/ibc-go/milestone/34)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] Compatibility tests pass.
- [x] Upgrade test pass.
- [x] Interchain Accounts inter-tx tests pass.

## Migration 

[v6 to v7 migration docs](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v6-to-v7.md)

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v6` to `github.com/cosmos/ibc-go/v7`.
- [x] Branch off main to create release branch in the form  of `release/v7.0.x` and add branch protection rules.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml).
- [x] Set up compatibility tests for `release/v7.0.x`. 
- [x] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check migration docs.
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [x] Update docs site:
  - [x] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [x] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L62).
- [x] Bump ibc-go version in [cosmos/interchain-accounts-demo repository](https://github.com/cosmos/interchain-accounts-demo) and create a tag.
- [x] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) and [e2e `icad`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-icad.yaml) test workflows:
  - Add the new release and the new `icad` tag.
  - Remove any tags that might not be recommended anymore.
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [x] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by gjermundgaraba** [comment]
Looking at the tracking it looks like this is getting pretty close. Are there any plans for a beta or rc release? We would like to start testing v7 on our 0.47-rc chain.

**Comment by crodriguezvega** [comment]
> Edit: nevermind me... I missed the fact that a beta had been tagged, because I was just looking in the releases section. Sorry about that... Carry on!

Indeed, we tagged [`v7.0.0-beta2`](https://github.com/cosmos/ibc-go/releases/tag/v7.0.0-beta2) last week and we will have the first RC probably next week at the latest.

**Comment by crodriguezvega** [comment]
[Compatibility tests pass](https://github.com/cosmos/ibc-go/actions/runs/4358374657) before v7.0.0-rc1.

Will run upgrade and interchain accounts test after tagging rc1.

**Comment by crodriguezvega** [comment]
Before final release:

- [x] [Compatibility tests pass](https://github.com/cosmos/ibc-go/actions/runs/4437183641).
- [x] [Upgrade test pass](https://github.com/cosmos/ibc-go/actions/runs/4442793133).
- [x] [Interchain Accounts inter-tx test pass](https://github.com/cosmos/interchain-accounts-demo/actions/runs/4450790198).

**Comment by crodriguezvega** [comment]
Closed by [v7.0.0](https://github.com/cosmos/ibc-go/releases/tag/v7.0.0)

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
