### ISSUE TITLE
Migrate params to be self managed

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#2010]
## Summary

Migrate all our on-chain params to be self managed, the SDK is removing x/param

See example [pr](https://github.com/cosmos/cosmos-sdk/pull/12363)

See upgrading [docs](https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#modules)

Ensure unset module params don't cause a panic on genesis export

The module will be removed after April 18th, 2023

### Issues:

- [x] #3500
- [x] #3501
- [x] #3502
- [x] #3503
- [x] #3504
- [ ] ~~#3621~~ Since there is no timeline for this yet, I'll remove it as requirement to close the epic issue.
- [x] #3704
- [x] #3705
- [ ] Add param e2es to compatibility tests.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Looking at the [PR for migrating `x/mint`](https://github.com/cosmos/cosmos-sdk/pull/12363) it looks like we need to:

In `tx.proto`:

- Add an [`UpdateParams` RPC endpoint](https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/mint/v1beta1/tx.proto#L20) to update params that receives a [`MsgUpdateParams`](https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/mint/v1beta1/tx.proto#L26) and returns a  [`MsgUpdateParamsResponse`](https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/mint/v1beta1/tx.proto#L43). Add the `Msg` service if needed.

In `types/msgs.go`:
- [Implement `sdk.Msg` for `MsgUpdateParams`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/types/msgs.go).

In `keeper/msg_server.go`:
- Implement [RPC endpoint for `UpdateParams`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/msg_server.go#L27).

In `types/keys.go`:
- Add key [`ParamsKey`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/types/keys.go#L6). This is the key that will be used to store the params.

In `keeper/keeper.go`:
- Add an [`authority` field to the `Keeper` struct](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/keeper.go#L25). This is the address capable of executing a `MsgUpdateParams` message, which will typically be the `x/gov` module account.
- Add [getter function to `Keeper` type to return the `authority`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/keeper.go#L54).
- Remove `paramSpace paramtypes.Subspace` from `Keeper` struct.
- Add [`GetParams` and `SetParams` functions](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/keeper.go#L82-L105) 

Since `NewKeeper` takes an `authority` parameter (this is an API breaking change), we should adjust calls to pass in as authority `authtypes.NewModuleAddress(govtypes.ModuleName).String()`.

And further:
- Create an [`exported/exported.go` file](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/exported/exported.go) that will be used for the migration and can be removed at a later release.
- Write [migration function](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/migrations/v2/migrate.go#L21) and expose it [via the `Migrator`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/migrator.go#L28).
- Add a [`legacySubspace` field` to the `Migrator`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/keeper/migrator.go#L12).

In `module.go`:
- Add a [`legacySubspace` field in `AppModule`](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/module.go#L103) because it needs to be passed to the [`NewMigrator` constructor function] (https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/module.go#L154). This is an API breaking change.
- [Bump the consensus version](https://github.com/cosmos/cosmos-sdk/blob/main/x/mint/module.go#L34).

I believe we need to do this for:
- 02-client 
- 03-connection
- transfer
- 27 host
- 27 controller

I guess we will need to adjust the existing tests setting params for [03-connection](https://github.com/cosmos/ibc-go/blob/main/e2e/tests/core/03-connection/connection_test.go#L50) and transfer ([this](https://github.com/cosmos/ibc-go/blob/main/e2e/tests/transfer/base_test.go#L230) and [this](https://github.com/cosmos/ibc-go/blob/main/e2e/tests/transfer/base_test.go#L280)).

**Comment by crodriguezvega** [comment]
When working on this we need to update the documentation at the bottom [here](https://ibc.cosmos.network/main/ibc/light-clients/setup.html) regarding adding a light to the list of allowed clients via a param change governance proposal.

**Comment by damiannolan** [comment]
We should add an upgrade handler and e2e chain upgrade test for v7 -> v8 which performs the migrations and does some parameter lookups and assertions to make sure everything is set correctly.
