### ISSUE TITLE
v6.0.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2272]
This release's main addition is the ICA improvements.

These improvements tackle two shortcomings of the current implementation of ICS-27:

- The lack of a default/standard underlying app (also known as authentication module), which created a bottleneck for chains looking to integrate the controller submodule.
- The need to separate application and authentication concerns.

The changes will make integrating the controller chain functionality easier (see [ADR 009](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-009-v6-ics27-msgserver.md) for more information), and with the release of Cosmos SDK v0.46.x, they will enable any Cosmos SDK module (e.g x/auth, x/gov, x/group) to register interchain accounts and send transactions on their behalf.

For more details about these changes, please read [this blog post](https://medium.com/the-interchain-foundation/ibc-go-v6-changes-to-interchain-accounts-f9996449d782).

Other features/improvements:

- ICS-20:
  - Adding a metadata field in FungibleTokenPacketData (implementation of https://github.com/cosmos/ibc/pull/842 spec - update).
  - Adding the sequence number of the packet sent to MsgTransferResponse.

- 04-channel:
  - Simplify SendPacket API (implementation of https://github.com/cosmos/ibc/pull/731 spec update).

## Milestones

[v6.0.0 milestone](https://github.com/cosmos/ibc-go/milestone/35)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] Compatibility tests pass.
- [x] Upgrade test pass.
- [x] Interchain Accounts inter-tx tests pass.

## Migration 

[Migration docs](https://github.com/cosmos/ibc-go/blob/release/v6.0.x/docs/migrations/v5-to-v6.md).

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v5` to `github.com/cosmos/ibc-go/v6`.
- [x] Branch off main to create release branch in the form  of `release/v6.0.x`.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [x] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check documentation and migration docs are up-to-date.
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md).
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [x] Update docs site:
  - [x] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [x] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L33).
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [x] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
[Compatibility test](https://github.com/cosmos/ibc-go/actions/runs/3538964675) ad [upgrade test](https://github.com/cosmos/ibc-go/actions/runs/3539558233) runs pre-rc1.

**Comment by crodriguezvega** [comment]
Test runs pre final release:

- [Compatibility tests pass](https://github.com/cosmos/ibc-go/actions/runs/3620095223).
- [Upgrade tests pass](https://github.com/cosmos/ibc-go/actions/runs/3647756039).
- [Interchain accounts inter-tx tests pass](https://github.com/cosmos/interchain-accounts-demo/actions/runs/3638202108).

**Comment by crodriguezvega** [comment]
Closed by [v6.0.0](https://github.com/cosmos/ibc-go/releases/tag/v6.0.0).
