### ISSUE TITLE
Interchain Accounts Tracking Issue

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#257]
This is a tracking issue for merging interchain-accounts into ibc-go. It is currently a [branch](https://github.com/cosmos/ibc-go/tree/interchain-accounts). This issue will be updated over time with more information as development continues. There will also be a milestone to track interchain account issues

Main milestones:
- [x] Code coverage (unit test additions)
- [x] Internal Audit
- [ ] alpha pre-release for early testers
- [ ] Audit by Informal Systems

**Comment by seantking** [comment]
Can we close this...seems like a duplicate of the actual milestone + we merged it into main :)

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
