### ISSUE TITLE
authz/ics20: review comments for initial PR

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#2960]
Initial [PR](https://github.com/cosmos/ibc-go/pull/2795).

- [x] Rename [allowed_addresses](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/proto/ibc/applications/transfer/v2/authz.proto#L20) to `allow_list` and [use in the protodoc the same comment as SDK in `authz.proto` for send](https://github.com/cosmos/cosmos-sdk/blob/3bb27795742dab2451b232bab02b82566d1a0192/proto/cosmos/bank/v1beta1/authz.proto#L25). @damiannolan 
- [x] Make [`IsAllowedAddress`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/modules/apps/transfer/types/transfer_authz.go#L39) private. @chatton #2985
- [x] Rename [`PortChannelAmount`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/proto/ibc/applications/transfer/v2/authz.proto#L11) to `Allocation`. @damiannolan 
- [x] Rename [`transfer_authz.go`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/modules/apps/transfer/types/transfer_authz.go#L39) to `transfer_authorization.go` and `transfer_authz_test.go` to `transfer_authorization_test.go`. @chatton #2990
- [x] Rename [`ErrDuplicateEntry`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/modules/apps/transfer/types/errors.go#L17) to `ErrInvalidAuthorization` and change the error text to `invalid transfer authorization` (see this [comment](https://github.com/cosmos/ibc-go/pull/2795#discussion_r1050155368)). @chatton #2988
- ~Replace usage of [this constant](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/modules/apps/transfer/types/transfer_authz.go#L12) with [SDK's](https://github.com/cosmos/cosmos-sdk/blob/main/x/authz/keeper/keeper.go#L21-L24).~ **constant is not exported, would require changes to the SDK to do this**
- [x] Format errors returned as `sdkerrors.Wrap(<type>, <message>)` instead of `sdkerrors.<type>.Wrapf(<message>)`. @chatton 
- [x] Move [`authz.proto`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/proto/ibc/applications/transfer/v2/authz.proto#L11) to `proto/ibc/applications/transfer/v1`. @damiannolan 
- [x] Convert [`NewTransferAuthorization`](https://github.com/cosmos/ibc-go/blob/feat/authz-ics20/modules/apps/transfer/types/transfer_authz.go#L19) into a variadic function: @damiannolan 

```golang
func NewTransferAuthorization(allocations ...Allocation) *TransferAuthorization {
	return &TransferAuthorization{
		Allocations: allocations,
	}
}
```

Separate PRs against the [feature branch](https://github.com/cosmos/ibc-go/tree/feat/authz-ics20) can be opened for each of these items.

**Comment by damiannolan** [comment]
Will tag myself beside tasks as I pick them up
