### ISSUE TITLE
Add `09-localhost` client state implementation

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#3034]
## Summary

Based on the work in https://github.com/cosmos/ibc-go/pull/2700, add a new client state implementation for `09-localhost`. 
The localhost client should be accompanied by a sentinel localhost `connectionEnd` which should be stored in state upon `InitGenesis` or enabed via a chain upgrade migration handler. 

Update the `09-localhost` client in https://github.com/cosmos/ibc-go/pull/2700 to conform to the latest `ClientState` implementation in ibc-go/v7. A feature branch has been created [here](https://github.com/cosmos/ibc-go/compare/09-localhost?expand=1). 

The body of work is detailed in the following issues:

- [x] https://github.com/cosmos/ibc-go/issues/3056
- [x] https://github.com/cosmos/ibc-go/issues/3058
- [x] https://github.com/cosmos/ibc-go/issues/3031
- [x] https://github.com/cosmos/ibc-go/issues/3032
- [x] https://github.com/cosmos/ibc-go/issues/3099
- [x] https://github.com/cosmos/ibc-go/issues/3033
- [x] https://github.com/cosmos/ibc-go/issues/3055
- [x] https://github.com/cosmos/ibc-go/issues/2537
- [x] https://github.com/cosmos/ibc-go/issues/3167
- [x] https://github.com/cosmos/ibc-go/issues/3166
- [x] #3193
- [x] https://github.com/cosmos/ibc-go/issues/3194
- [x] https://github.com/cosmos/ibc-go/issues/3206
- [x] https://github.com/cosmos/ibc-go/issues/3208

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
