### ISSUE TITLE
v7.1.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3038]
Main additions to this release are:

#### Localhost client

This feature will add support for applications on a chain to communicate with applications on the same chain using the existing standard interface to communicate with applications on remote chains. This is a powerful UX improvement, particularly for those users interested in interacting with multiple smart contracts on a single chain through one interface.

A special shout out to Strangelove and Polymer Labs for their substantial contribution on this feature.

## Milestones

[v7.1.0 milestone](https://github.com/cosmos/ibc-go/milestone/37)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-compatibility.yaml) pass for the release branch.
- [x] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-upgrade.yaml) pass.
- [ ] [Interchain Accounts inter-tx tests](https://github.com/cosmos/interchain-accounts-demo/actions/workflows/e2e-compatibility.yaml) pass.

## Checklist

- [x] Branch off from v7.0.0 to create release branch in the form  of `release/v7.1.0`.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml).
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [ ] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [x] Update docs site:
  - [x] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [x] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L62).
- [ ] Bump ibc-go version in [cosmos/interchain-accounts-demo repository](https://github.com/cosmos/interchain-accounts-demo) and create a tag.
- [x] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) and [e2e `icad`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-icad.yaml) test workflows:
  - Add the new release and the new `icad` tag.
  - Remove any tags that might not be recommended anymore.
- [ ] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Test runs before release:
- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/runs/5214462963)
- [x] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/runs/5216875984)
