### ISSUE TITLE
[EPIC] IBC-Go Documentation Revamp

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#3488]
## Summary
This epic focuses on revamping the ibc-go documentation to improve usability, structure, and content.

## Problem Definition
The current documentation has certain limitations, such as deprecated dependencies and an inefficient structure. We aim to create a more comprehensive and user-friendly documentation system to ensure users can quickly and easily access the information they need.

## Work Breakdown
- [x] #3492
- [x] #3522
- [x] #3623
- [ ] Create and organize a glossary section.
- [ ] Reorganize sections for better navigation and understanding.
- [x] #3534
- [x] #4932
____
#### For Admin Use
- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by colin-axner** [comment]
Saw this issue while going through older issues. Wondering if we should close it and open up issues for any individual changes we still want to make? But the doc site looks pretty good to me nowadays
