### ISSUE TITLE
Support SDK dependency injection for v2 apps

### ISSUE THREAD

**Issue by alpe** [cosmos/ibc-go#3560]
## Summary
SDK 47 ships with the new dependency-injection framework used in [app_v2](https://github.com/cosmos/cosmos-sdk/blob/v0.47.2/simapp/app_v2.go#L204).

As wasmd has a dependency to the ibc (core and other) keepers, we can not update our module to be used with the dependency-injection framework. 
There is no workaround AFAIK

## Proposal
Please make the modules compatible to work with app v1 + v2.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Thank you, @alpe, for opening this issue. How pressing is your need to have ibc-go compatible with app v2? Having also app v1 is blocking any urges development on your side?

**Comment by alpe** [comment]
The v1 app is working with our sdk v47 integration. But as v2 had become the "preferred" setup (in build tags) we were eager to provide a fully compatible module with our official release.
This is not possible due to our dependency on ibc-go in the wasmd module. We set the new goal for v2 support in the v0.41 release.
Therefore it is not super urgent but blocking the integration work on our side.

**Comment by crodriguezvega** [comment]
Thanks for the information, @alpe. What is your timeline for v0.41? 

And If I understand correctly, then you would like to have this available in the v7 release line, right?

**Comment by alpe** [comment]
v7.x would be nice to have a small change set only. 
We don't have a strict release schedule for v0.41 but target middle of April. As the work on our side had started already, it would be great to not have this pending for too long.

In https://github.com/CosmWasm/wasmd/pull/1287 we have a mixed v2 with v1 legacy module setup in /app. That could be some template for your test setup before adding full v2 support to the module.

**Comment by crodriguezvega** [comment]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by crodriguezvega** [comment]
- [ ] Add buf pulsar generation (in progress, branch [here](https://github.com/cosmos/ibc-go/tree/carlos/add-buf-gen-pulsar) -[previous PR](https://github.com/cosmos/ibc-go/pull/4039)).
- [ ] Add depinject support to code module (in progress, branch [here](https://github.com/cosmos/ibc-go/tree/carlos/3560-depinject-support-code) - [previous PR](https://github.com/cosmos/ibc-go/pull/4040))
- [ ] Add depinject support to transfer module.
- [ ] Add depinject support to 29-fee module.
- [ ] Add depinject support to 27-interchain-accounts module.
- [ ] Add depinject support to 06-solomachine module.
- [ ] Add depinject support to 07-tendermint module.
- [ ] Add depinject support to 08-wasm module.

All the branches to add support to a module will need to branch off [carlos/add-buf-gen-pulsar](https://github.com/cosmos/ibc-go/tree/carlos/add-buf-gen-pulsar).

Do we need also to add support in the mock module?

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
