### ISSUE TITLE
Upgrade to Cosmos SDK v0.50 (Eden)

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3707]
Tracking issue for the upgrade to the next Cosmos SDK version.

Tentatively planning the upgrade for v8.0.0, but leaving the option open to change.

- [x] https://github.com/cosmos/ibc-go/pull/3883
- [x] https://github.com/cosmos/ibc-go/issues/3911
- [x] https://github.com/cosmos/ibc-go/issues/4217

**Comment by faddat** [comment]
Hey, I've got a few updates here:

* #4395 
* #4393 
* #4396 
* #4392 

So, thing is that all of these are interlinked.  I apologize, not every one is passing, and they're a bit inter-dependent.  I was unable to bump the capability module without updating to go 1.21.  

Then I noticed that I had not updated interchaintest correctly.  I do have a PR on interchaintest that attempts to update it to sdk 50, and it feels like it is "close"

* https://github.com/strangelove-ventures/interchaintest/pull/696 <- related because of changes in wasmd

**Comment by bizk** [comment]
We are trying to upgrade Rosetta tool to sdk v0.50 as well.  It depends on this package, so we are interested on the development of this task :) Let us know if we can provide any info that might be helpful

**Comment by crodriguezvega** [comment]
@bizk Thank you for the offer! Our latest tag with the upgrade work is [upgrade-sdk-v0.50-alpha2](https://github.com/cosmos/ibc-go/tree/). This tag is using v0.50-rc.0. We are actively working on this at the moment (getting our e2e tests green), so more tags should follow soon.
