### ISSUE TITLE
v8.0.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3814]
This release main additions are:

#### Upgrade SDK v0.50

See the [tracking issue](https://github.com/cosmos/ibc-go/issues/3707) for more information.

#### Migration of gov proposals from v1beta1 to v1

See the [epic issue](https://github.com/cosmos/ibc-go/issues/1282) for more information.

#### Migration of params to be self managed

See the [epic issue](https://github.com/cosmos/ibc-go/issues/2010) for more information.

## Milestones

[v8.0.0 milestone](https://github.com/cosmos/ibc-go/milestone/38)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-compatibility.yaml) pass for the release branch.
- [ ] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-upgrade.yaml) pass.
- [x] Manual test with ledger signing

### Other testing

TBD integration testing with third parties.

## Migration 

[v7 to v8 migration docs](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/v7-to-v8.md)

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v7` to `github.com/cosmos/ibc-go/v8`.
- [x] Branch off main to create release branch in the form  of `release/v8.0.x` and make sure branch protection rules apply.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [x] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [x] Update docs site:
  - [ ] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [ ] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L62).
- [x] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) test workflow and remove any tags that might not be recommended anymore.
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [x] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
[Green compatibility tests](https://github.com/cosmos/ibc-go/actions/runs/6534563757) at https://github.com/cosmos/ibc-go/commit/c592a8dfa6ca55f07bf7232c9cdf69d61916716b.

**Comment by crodriguezvega** [comment]
[Green compatibility tests](https://github.com/cosmos/ibc-go/actions/runs/6814749338) at 4ee44a03e529ccc63467af85c63c3c16d8132215 (before final v8.0.0).

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/releases/tag/v8.0.0.
