### ISSUE TITLE
v7.3.0 tracking issue

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#3815]
Main additions to this release are:

#### JSON encoding of ICA transactions

See [this issue](https://github.com/cosmos/ibc-go/issues/3246) for more information. Including this feature in the release depends on whether the implementation can be back ported to the release branch of v7.3.x.

#### Support for ADR 8 middleware

[Adding an optional interface](https://github.com/cosmos/ibc-go/pull/3287) that IBC applications can implement for their packet data, such that, when implemented, middleware can target this interface in order to get the desired callback addresses on the source and destination chains.

## Milestones

[v7.3.0 milestone](https://github.com/cosmos/ibc-go/milestone/39)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-compatibility.yaml) pass for the release branch.
- [ ] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-upgrade.yaml) pass.

### Other testing

TBD integration testing with third parties.

## Migration 

v7.1 to v7.3 migration docs (add link when available).

## Checklist

- [x] Branch off `release/v7.2.x` to create release branch in the form  of `release/v7.3.x` and make sure branch protection rules apply.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [ ] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [ ] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [x] Update docs site:
  - [ ] Add new release branch to [`docs/versions`](https://github.com/cosmos/ibc-go/blob/main/docs/versions) file.
  - [ ] Add `label` and `key` to `versions` array in [`config.js`](https://github.com/cosmos/ibc-go/blob/main/docs/.vuepress/config.js#L62).
- [x] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) test workflow and remove any tags that might not be recommended anymore.
- [x] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [ ] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
[Green compatibility tests](https://github.com/cosmos/ibc-go/actions/runs/6036297540) before final release.
