### ISSUE TITLE
Fee middleware

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#396]
Requirements document (coming soon...)
[ICS-29 spec](https://github.com/cosmos/ibc/tree/master/spec/app/ics-029-fee-payment)
[Project board](https://github.com/orgs/cosmos/projects/7/views/8)

## ADRs

- [ADR 004: Lock fee module upon escrow out of balance](https://github.com/cosmos/ibc-go/blob/main/docs/architecture/adr-004-ics29-lock-fee-module.md)

## Milestones

- [Alpha](https://github.com/cosmos/ibc-go/milestone/5)
- [Beta](https://github.com/cosmos/ibc-go/milestone/23)
- [RC](https://github.com/cosmos/ibc-go/milestone/24)

## Pre-releases

- [ics29-alpha1](https://github.com/cosmos/ibc-go/releases/tag/ics29-alpha1)
- [ics29-beta1](https://github.com/cosmos/ibc-go/releases/tag/ics29-beta1)
- [ics29-beta2](https://github.com/cosmos/ibc-go/releases/tag/ics29-beta2)

### Channel handshake 

- [x] Check fee-enabled transfer channel handshake completes when both chains support fee middleware. 
- [x] Check fee-enabled interchain channel handshake completes when both chains support fee middleware.

Check handshake is backwards compatible (one chain with fee middleware, other chain without fee middleware):
- [x] Check non-fee transfer channel handshake completes when started from the chain with fee middleware.
- [x] Check non-fee transfer channel handshake completes when started from the chain without fee middleware.
- [x] Check non-fee interchain account channel handshake completes when started from the chain with fee middleware.
- [x] Check non-fee interchain account channel handshake completes when started from the chain without fee middleware.

### Token transfers with two chains that support fee middleware
 
Using `MsgPayPacketFee`:
- [x] When packet is incentivized from single sender AND token transfer succeeds, then recv, ack fees are paid.
- [x] When packet is incentivized from multiple senders AND token transfer succeeds, then recv, ack fees are paid.
- [x] When packet is incentivized from single sender AND token transfer times out, then timeout fees are paid.
- [x] When packet is incentivized from multiple senders AND token transfer times out, then timeout fees are paid.
- [x] When packet is incentivized from single sender AND counterparty payee address is not set AND token transfer succeeds, then recv fees are refunded.
- [x] When packet is incentivized from single sender AND payee is set AND token transfer succeeds, then ack fees are paid to payee address instead of relayer address.
- [x] When packet is incentivized from single sender AND payee is set AND token transfer times out, then timeout fees are paid to payee address instead of relayer address.
- [x] Incentivization with ledger.

Using `MsgPayPacketFeeAsync`:
- [x] When packet is incentivized from single sender AND token transfer succeeds, then recv, ack fees are paid.
- [x] When packet is incentivized from multiple senders AND token transfer succeeds, then recv, ack fees are paid.
- [x] When packet is incentivized from single sender AND token transfer times out, then timeout fees are paid.
- [x] When packet is incentivized from multiple senders AND token transfer times out, then timeout fees are paid.
- [x] When packet is incentivized from single sender AND counterparty payee address is not set AND token transfer succeeds, then recv fees are refunded.
- [x] When packet is incentivized from single sender AND payee is set AND token transfer succeeds, then ack fees are paid to payee address instead of relayer address.
- [x] When packet is incentivized from single sender AND payee is set AND token transfer times out, then timeout fees are paid to payee address instead of relayer address.
- [x] Escrow to an already complete packet is rejected.
- [x] Escrow to a packet that does not exist is rejected.
- [x] Incentivization with ledger.

### Interchain accounts with two chains that support fee middleware

Using `MsgPayPacketFee`:
- [x] When packet is incentivized from single sender AND ICA message is executed by host, then recv, ack fees are paid.
- [x] When packet is incentivized from multiple senders AND ICA message is executed by host, then recv, ack fees are paid.
- [x] When packet is incentivized from single sender AND ICA message to host times out, then timeout fees are paid.
- [x] When packet is incentivized from multiple senders AND ICA message to host times out, then timeout fees are paid.
- [x] When packet is incentivized from single sender AND counterparty payee address is not set AND ICA message is executed by host, then recv fees are refunded.
- [x] When packet is incentivized from single sender AND payee is set AND ICA message is executed by host, then ack fees are paid to payee address instead of relayer address.
- [x] When packet is incentivized from single sender AND payee is set AND ICA message to host times out, then timeout fees are paid to payee address instead of relayer address.

Using `MsgPayPacketFeeAsync`:
- [x] When packet is incentivized from single sender AND ICA message is executed by host, then recv, ack fees are paid.
- [x] When packet is incentivized from multiple senders AND ICA message is executed by host, then recv, ack fees are paid.
- [x] When packet is incentivized from single sender AND ICA message to host times out, then timeout fees are paid.
- [x] When packet is incentivized from multiple senders AND ICA message to host times out, then timeout fees are paid.
- [x] When packet is incentivized from single sender AND counterparty payee address is not set AND ICA message is executed by host, then recv fees are refunded.
- [x] When packet is incentivized from single sender AND payee is set AND ICA message is executed by host, then ack fees are paid to payee address instead of relayer address.
- [x] When packet is incentivized from single sender AND payee is set AND ICA message to host times out, then timeout fees are paid to payee address instead of relayer address.
- [x] Escrow to an already complete packet is rejected.
- [x] Escrow to a packet that does not exist is rejected.

### Migration

- [x] Test that [genesis state](https://github.com/cosmos/ibc-go/blob/main/modules/apps/29-fee/types/genesis.pb.go#L28-L39) can be correctly exported and imported.

## Checklist

- [x] Internal audit(s).
- [x] External audit(s).
- [x] Documentation.
- [x] Swagger.
- [x] Integration with relayers:
    - [x] Hermes
    - [ ] Rly

**Comment by crodriguezvega** [comment]
Released in [v4.0.0](https://github.com/cosmos/ibc-go/releases/tag/v4.0.0).
