### ISSUE TITLE
Allow Unordered ICA Channels

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-go#3996]
## Summary

Currently, ICA only allows ordered channels. This causes the channel to close if a timeout occurs, forcing the user to reopen it.

## Problem Definition

ICA only allows ordered channels because if ordering is not enforced, then the relayer could try malicious attacks by reordering/censoring some of the ica-controller's transactions. However, this requirement can be dropped because the ica-controller can choose not to send any new transactions until it receives an acknowledgement or a timeout packet.

## Proposal

```[tasklist]
- [ ] https://github.com/cosmos/ibc-go/issues/5522
- [ ] https://github.com/cosmos/ibc-go/issues/5523
- [ ] https://github.com/cosmos/ibc-go/issues/5524
- [ ] https://github.com/cosmos/ibc-go/issues/5580
- [ ] https://github.com/cosmos/ibc-go/issues/5629
- [ ] https://github.com/cosmos/ibc-go/issues/5602
- [ ] https://github.com/cosmos/ibc-go/issues/5605
- [ ] https://github.com/cosmos/ibc-go/issues/5525
- [ ] https://github.com/cosmos/ibc-go/issues/5534
- [ ] https://github.com/cosmos/ibc-go/issues/5526
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by migueldingli1997** [comment]
This would be very helpful for our use-case as well. We are using ICA round the clock with low timeout values for the transactions (because we want them to pass in a narrow time range, or not pass). If there is any event that causes this timeout then we're suddenly stuck with a closed channel that has to be re-opened.

**Comment by womensrights** [comment]
Great to hear you are using ICA! Could you tell us a bit more about your precise use case if you are happy for it to be public? We had heard that ordered channels for ICA was a pain point for a few users but when we looked in more detail at the number of channel closures happening is actually really small. For example on Stride, the number of ICA timeouts has been 40/ 35,261 which is 0.11% of transactions since genesis and for Quicksilver it was 68 of 312,565 ICA txs since Jan. so approx 0.02% therefore the change would be a relatively small improvement it seems but would like to hear more about your own experience

**Comment by hxrts** [comment]
> approx 0.02% therefore the change would be a relatively small improvement it seems

I think this may be due to survivorship bias. I know most relayers don't want to run ICAs because it's too error prone and complex. Devs have a much harder time building applications because ICA relay channels are harder to come by. You should speak to some of the devs from the recent Dora hackathon within the Neutron track at Cosmoverse. The challenge required devs to use ICA and most people gave up because it was too difficult.

**Comment by joe-bowman** [comment]
> Quicksilver it was 68 of 312,565 ICA txs since Jan. so approx 0.02% therefore the change would be a relatively small improvement 

'Small improvement' in percentage of overall terms, but the wasted hours of finding, fixing and working around channel closures has been an expensive past time :) 

'Big improvement' in DevX.

**Comment by joe-bowman** [comment]
Apologies; it was not my intention to suggest so :) great to see the spec is merged, I’m looking forward to it!
