### ISSUE TITLE
v2.0.0 Release Tracking Issue

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#421]
v2.0.0 Release Team: @colin-axner @crodriguezvega 

Community feedback indicates there is a desire for a release to be made including a fix to #329. This fix is API and state machine breaking. As noted in our [Releases](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md) documentation, an API breaking change will result in a major version bump. 

The scope of this release is very small and primarily intended to fix #329. We have elected to include a few small unreleased changes. This includes two minor API breaking changes. These will require minor modifications to IBC applications who wish to update to this version. More information can be read in the [migration docs](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/ibc-migration-v100.md#ibc-apps).

For this release cycle, we will do a beta release, rc series and finally a final v2.0.0 release. A release branch will be created when a beta release is ready to be made. Any subsequent bug fixes must be backported to the release branch.

**Beta release requirements:**

- [x] fix #329 - #350
- [x] bump go package version - #400 
- [x] update migration docs - #401

**RC release requirements:**

- [x] v2.0.0 works with Hermes 
- [x] v2.0.0 works with ts-relayer
- [x] any chain using the v2.0.0 can communicate with existing chains using amounts <= max(int64)
- [x] new chains both using v2.0.0 can communicate using amounts <= max(uint256)
- [x] new chains sending amounts > max(int64) interact with expected behaviour (sending back a failed ack or allowing for a timeout)

A final release will be made after no issues are reported during the RC stage after a sufficient amount of time (undetermined at the moment). No migrations are required to update to v2.0.0, only a coordinated upgrade. v2.0.0 ibc-go is fully compatible with IBC spec v1.0

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closing because [v2.0.0](https://github.com/cosmos/ibc-go/releases/tag/v2.0.0) is out now.
