### ISSUE TITLE
Refactor `ChanUpgradeTimeout` to follow latest spec

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#4421]
## Summary

Refactor the `ChannelUpgradeTimeout` rpc handler to follow and align with the new specification.

[ref](https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md#timeout-upgrade-process)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

```[tasklist]
### Tasks
- [x] Update the 04-channel `ChanUpgradeTimeout` handler
- [x] Update the 04-channel `WriteUpgradeTimeoutChannel` function
- [x] Update the core msg server `ChannelUpgradeTimeout` rpc entrypoint
- [x] Uncomment and adjust tests as required
```
