### ISSUE TITLE
Documentation for channel upgradability

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5089]
Write documentation for channel upgradability (maybe in a subsection of `Using IBC-Go`).
Each task may be tacked in a separate PR.

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/ibc-go/issues/5267
- [ ] https://github.com/cosmos/ibc-go/issues/5268
- [ ] https://github.com/cosmos/ibc-go/issues/5269
- [ ] https://github.com/cosmos/ibc-go/issues/5270
- [ ] https://github.com/cosmos/ibc-go/issues/5271
- [ ] https://github.com/cosmos/ibc-go/issues/5272
- [ ] https://github.com/cosmos/ibc-go/issues/5273
- [ ] https://github.com/cosmos/ibc-go/issues/4277
- [ ] https://github.com/cosmos/ibc-go/issues/5501
```
