### ISSUE TITLE
Items from channel upgradability alpha walkthrough

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5201]
Each task can be completed in a different PR. Please open an issue for the task you plan to pick up and assign it to yourself.

```[tasklist]
### Tasks
- [ ] Godoc of `validateSelfUpgradeFields` needs to be updated (order doesn’t need to be a subset - remove [this line](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L826).
- [ ] Change the error returned (`ErrChannelExists`) in `validateSelfUpgradeFields` when [the proposed upgrade fields match the channel current parameters](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L834).
- [ ] Add comment in `ChanUpgradeInit` that a [nil timeout is intentionally returned](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L41) as it is set later.
- [ ] Return in `MsgChannelUpgradeInitResponse` only the upgrade version and the upgrade sequence.
- [ ] Panic in `WriteErrorReceipt` [instead of returning an error](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L932), which is ignored.
- [ ] Pass upgrade version into WriteUpgrade<HandshakeStep> func
- [ ] In `ChanUpgradeTry` move [fast forward sequence](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L118-L122) down below after the call to `ChanUpgradeInit`.
- [ ] Remove `latestPacketSend` from [`NewUpgrade` constructor](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/types/upgrade.go#L15).
- [ ] Add comment above [this line](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L226) or in the godoc (channel state is open, if chain executed init; or flushing, if it executed try).
- [ ] Add comment [when setting the version to counterparty version](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L282) that the optimstism refers to failing in `OnChanOpenAck` callback.
- [ ] `WriteUpgradeAckChannel` should have errors instead of just string (replace `fmt.Sprintf` with `fmt.Errorf`).
- [ ] Add comment above [this line](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/upgrade.go#L319) to explain what the counterparty upgrade is used for.
- [ ] In `ChanUpgradeTry` it might be nice to add a note that we explicitly only set error receipts, the upgrade will not be aborted until it is proved to be incompatible in ChanUpgradeAck`.
- [ ] Switch [these 2 lines](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/keeper/msg_server.go#L930-L931) around to make it consistent with the spec.
- [ ] Change [this condition](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L156) so that if the counterparty upgrade is found then we execute the code below, otherwise we just continue instead of returning an error.
- [ ] Remove setting counterparty upgrade info in upgrade try, only set once we have the full counterparty upgrade. After this we can simplify the if statement when moving from flushing to flushing complete in packet and timeout processing (it can assume the timeout is valid in counterparty upgrade and we can remove [this code](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L174-L176)). Apply the same changes [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/packet.go#L478-L498).
- [ ] Emit an event when we move to `FLUSHCOMPLETE` [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/timeout.go#L169) and [here](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/keeper/packet.go#L495).
- [ ] Proof in `MsgChannelUpgradeCancel` is allowed to be empty (gov override), so remove [this check](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/types/msgs.go#L850) in `ValidateBasic`.
- [ ] Allow [error receipt to be nil](https://github.com/cosmos/ibc-go/blob/39df8d2b579fc623a1e748b4330738ff40adb682/modules/core/04-channel/types/msgs.go#L854) in `ValidateBasic` for `MsgChannelUpgradeCancel`.
- [ ] Make sure that the error receipt we write always has a sequence greater than the existing one.
```

**Comment by hieuvubk** [comment]
Could I pick up some task?

**Comment by chatton** [comment]
@hieuvubk sure! Which one would you like to grab?

**Comment by hieuvubk** [comment]
> @hieuvubk sure! Which one would you like to grab?

5th & 6th I think, I cant edit the description for new issues :(((

**Comment by crodriguezvega** [comment]
> > @hieuvubk sure! Which one would you like to grab?
> 
> 5th & 6th I think, I cant edit the description for new issues :(((

Thank you, @hieuvubk. I opened issues for those. Can you comment on them? Then I will be able to assign them to you.

**Comment by ThanhNhann** [comment]
Hi @crodriguezvega, can you list all the issues above so I and another guys of my team can pick it? ❤️

**Comment by colin-axner** [comment]
Looks like we can close this issue now?
