### ISSUE TITLE
Release v8.1.0

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#5649]
This release main additions are:

#### Channel upgradability

Implementation of the [channel upgrades spec](https://github.com/cosmos/ibc/blob/c6907112b9fb0c675ad5824187549dd333c799d8/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md). See [alpha](https://github.com/cosmos/ibc-go/milestone/29), [beta](https://github.com/cosmos/ibc-go/milestone/42) and [RC](https://github.com/cosmos/ibc-go/milestone/45) milestones for more details.

#### Unordered ICA channels

New ICA channels will support unordered ordering, and with channel upgradability it will be possible to upgrade existing ICA ordered channels to change the ordering to unordered. See [this issue](https://github.com/cosmos/ibc-go/issues/3996) for more information.

For other improvements and fixes in this release, please check out the [`release/v8.1.x` changelog](https://github.com/cosmos/ibc-go/blob/release/v8.1.x/CHANGELOG.md#unreleased).

## Milestones

[v8.1.0 milestone](https://github.com/cosmos/ibc-go/milestone/46)

## IBC spec compatibility

v1.0

### Backwards compatibility

- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-compatibility.yaml) pass for the release branch.
- [x] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-upgrade.yaml) pass.

## Checklist

- [x] Branch off `release/v8.0.x` to create release branch in the form of `release/vx.y.z` and add branch protection rules.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [ ] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [x] Check Swagger is up-to-date.

## Post-release checklist

- [x] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [x] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [x] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [ ] Update docs site:
  - [x] If the release is occurring on the main branch, on the latest version, then run `npm run docusaurus docs:version vX.Y.Z` in the `docs/` directory. (where `X.Y.Z` is the new version number)
  - [ ] If the release is occurring on an older release branch, then make a PR to the main branch called `docs: new release vX.Y.Z` doing the following:
    - [ ] Update the content of the docs found in `docs/versioned_docs/version-vx.y.z` if needed. (where `x.y.z` is the previous version number)
    - [ ] Update the version number of the older release branch by changing the version number of the older release branch in:
      - [ ] In `docs/versions.json`.
      - [ ] Rename `docs/versioned_sidebars/version-vx.y.z-sidebars.json`
      - [ ] Rename `docs/versioned_docs/version-vx.y.z`
- [x] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [x] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) test workflow:
  - Remove any tags that might not be recommended anymore.
- [ ] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [ ] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

---

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/pull/5780.
