### ISSUE TITLE
Add light client implementation guide

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#59]
## Summary

A guide to implementing a light client for IBC
- [ ] overview (vocabulary - client/consensus states, client message etc ie each interface) #1850 
- [ ] client_state.go and its functions #1851 
- [ ] consensus_state.go and its functions #1852
- [ ] existence/non-existence proofs #1853
- [ ] update function #1854
- [ ] misbehaviour handling #1854
- [ ] upgrade handling
- [ ] proposal handling
- [ ] genesis metadata

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
Must note light client requirements such as:
- checking for misbehaviour on updates and freezing the client if misbehaviour is found
- checking for duplicate updates
- accounting for time and block delay

**Comment by colin-axner** [comment]
Every client state interface function should have a section and clearly document the requirements/expectations of that 02-client has for those functions. 

Explanation of types `ClientState`, `ConsensusState`, `ClientMessage` is needed. How misbehaviour submission works via `MsgUpdateClient`

**Comment by colin-axner** [comment]
Closing in favor the sub issues created. New requested additions to the light client guide should be opened in separate issues

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
