### ISSUE TITLE
Add methods for registering both IBC apps and lightclients through the `IBCKeeper` type

### ISSUE THREAD

**Issue by damiannolan** [cosmos/ibc-go#6146]
Add apis to allow for registering/adding routes of both ibc applications and lightclient modules through the `IBCKeeper` as one logical point.

I'm not sure this is the ideal approach but came to mind as something I thought was worth discussing - It may be applicable for depinject work as mentioned below, maybe not!

> I think there's some other improvements we could probably make to APIs of the core `IBCKeeper`. 
For example right now we require users to create a port router in app.go and bind ibc appmodules there, similarly we retrieve the new light client module router from the clientKeeper and `AddRoute` for each light client module. 

> It may be nice to have everything flow through the `IBCKeeper`, as it essentially is a facade around the set of submodules which make up core ibc. 

> e.g. `IBCKeeper.RegisterClientModule(lightClient)` and `IBCKeeper.RegisterIBCApplication` or something like that, could be useful at some point, maybe these changes may be warranted with depinject work so I think we can hold off on them for now and discuss later. Feel free to drop any thoughts 💭

_Originally posted by @damiannolan in https://github.com/cosmos/ibc-go/pull/6138#discussion_r1561037737_
            
```[tasklist]
### Tasks
- [ ] Define new APIs for `IBCKeeper` if direction is agreed upon
- [ ] Refactor core IBC to use the new APIs instead of accessing the 05-port `Router` directly
- [ ] Refactor app.go to use new APIs for registering ibc apps and light client modules
```

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
