### ISSUE TITLE
Release v9

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/ibc-go#6497]
This release main additions are:

#### ICS20 v2

- Support for [multi-denom transfers](https://github.com/cosmos/ibc/pull/1020).
- Support for [path forwarding](https://github.com/cosmos/ibc/pull/1090).
- Support for [protobuf encoding of packet data](https://github.com/cosmos/ibc/issues/1097).

#### 02-client router refactoring

- [Decouple 02-client routing from encoding](https://github.com/cosmos/ibc-go/issues/5565).

## Milestones

[v9.0.0](https://github.com/cosmos/ibc-go/milestone/44)
[ICS20 v2 (multi denom) alpha](https://github.com/cosmos/ibc-go/milestone/49)
[ICS20 v2 (multi denom) beta](https://github.com/cosmos/ibc-go/milestone/54)
[ICS20 v2 (multi denom) RC](https://github.com/cosmos/ibc-go/milestone/55)
[ICS20 v2 (path forwarding) alpha](https://github.com/cosmos/ibc-go/milestone/53)
[ICS20 v2 (path forwarding) beta](https://github.com/cosmos/ibc-go/milestone/57)
[ICS20 v2 (path forwarding) RC](https://github.com/cosmos/ibc-go/milestone/56)

## IBC spec compatibility

v1.0.0

### Backwards compatibility

- [x] [Compatibility tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-compatibility.yaml) pass for the release branch.
- [x] [Upgrade tests](https://github.com/cosmos/ibc-go/actions/workflows/e2e-upgrade.yaml) pass.
- [x] Manual test with ledger signing of IBC transfer.

## Checklist

- [x] Bump [go package version](https://github.com/cosmos/ibc-go/blob/main/go.mod#L3).
- [x] Change all imports starting with `github.com/cosmos/ibc-go/v8` to `github.com/cosmos/ibc-go/v9`.
- [x] Branch off main to create release branch in the form of `release/v9.0.x` and add branch protection rules.
- [x] Add branch protection rules to new release branch.
- [x] Add backport task to [`mergify.yml`](https://github.com/cosmos/ibc-go/blob/main/.github/mergify.yml)
- [ ] Upgrade ibc-go version in [ibctest](https://github.com/strangelove-ventures/ibctest).
- [ ] Check Swagger is up-to-date.

## Post-release checklist

- [ ] Update [`CHANGELOG.md`](https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md)
- [ ] Update the table of supported release lines (and End of Life dates) in [`RELEASES.md`](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md):
  - Add the new release line.
  - Remove any release lines that might have become discontinued.
- [ ] Update [version matrix](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#version-matrix) in `RELEASES.md`:
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [ ] Update the list of [supported release lines in README.md](https://github.com/cosmos/ibc-go#releases), if necessary.
- [ ] Update docs site:
  - [ ] Update permalinks with links of the released tag.
  - [ ] If the release is occurring on the main branch, on the latest version, then run `npm run docusaurus docs:version v9.0.x` in the `docs/` directory.
- [ ] Update the [compatibility test matrices](https://github.com/cosmos/ibc-go/tree/main/.github/compatibility-test-matrices):
  - Add the new release.
  - Remove any tags that might not be recommended anymore.
- [ ] Update the manual [e2e `simd`](https://github.com/cosmos/ibc-go/blob/main/.github/workflows/e2e-manual-simd.yaml) test workflow:
  - Remove any tags that might not be recommended anymore.
- [ ] After changes to docs site are deployed, check [ibc.cosmos.network](https://ibc.cosmos.network) is updated.
- [ ] Open issue in [SDK tutorials repo](https://github.com/cosmos/sdk-tutorials) to update tutorials to the released version of ibc-go.

---

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by crodriguezvega** [comment]
Green [compatibility](https://github.com/cosmos/ibc-go/actions/runs/10880480800) and [upgrade](https://github.com/cosmos/ibc-go/actions/runs/11116087505) tests before final release.

**Comment by crodriguezvega** [comment]
Closed by https://github.com/cosmos/ibc-go/releases/tag/v9.0.0.
