### ISSUE TITLE
Remove 03-connection layer

### ISSUE THREAD

**Issue by colin-axner** [cosmos/ibc-go#7134]
## Summary

With #6985 we see a direction of IBC which is simpler and more efficient, thus easier to implement in other languages and environments. The 03-connection layer should be removed. Here's why. 

## Problem Definition

The 03-connection layer has primarily served as a wrapper around the 02-client layer with additional information which is set during a connection handshake. This connection handshake ensured that clients were indeed properly configured and connected to one another. It could not verify if one side of the connection was malicious though. 

With the removal of client and consensus state validation https://github.com/cosmos/ibc/pull/1128, we can see that there isn't much left occurring in the [connection handshake](https://github.com/cosmos/ibc-go/blob/0bf8e8bc6611b5940ad455470f22f8c274feb783/modules/core/03-connection/keeper/handshake.go)

More or less we:
* generate connectionIDs
* negotiate a connection version (has never changed or been used)
* set the auxiliary client information in the connection 
* verify that the counterparty is performing actions (connection verification)

None of these are really necessary. 

If we look at the [connection structure](https://github.com/cosmos/ibc-go/blob/0bf8e8bc6611b5940ad455470f22f8c274feb783/proto/ibc/core/connection/v1/connection.proto#L17) we have:
* client id (already managed by 02-client)
* version (unused)
* state (unnecessary if you remove the connection end)
* counterparty (useful info, clientID + prefix, already being set used in eureka)
* delay period (see #7133)

The primary pieces which are useful and must be migrated:
* counterparty 
* delay period

## Proposal

I think a first step is to require connections initiated on our side to use eureka https://github.com/cosmos/ibc-go/issues/7004. This would remove `MsgConnOpenInit` and `MsgConnOpenAck`. In addition, once we perform `MsgConnOpenConfirm`, we could remove the connection end we were setting in state. We would need to modify the channel handshake to account for a missing connection

We unfortunately cannot do the same for `MsgChanOpenInit` and `MsgChanOpenAck` without making changes to interchain accounts controller module. 

Once all the below are checked, we can remove all references to the 03-connection layer:
- [ ] all chains are establishing new connections through eureka
- [x] #7133 
- [x] https://github.com/cosmos/ibc-go/issues/6975

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by womensrights** [comment]
We need a larger discussion around the long term migration from classic to eureka
