### ISSUE TITLE
EPIC: Olympus Upgrade (SDk 0.52)

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/ibc-go#7223]
## Description 

This issue is meant to encapsulate the todos in the code that will be removed when upgrading to 0.52/v2

- pass environment
  - remove logger methods in all modules
  - remove sdk.Context for things like gasservice, branchservice(cachectx), headerservice(block/headerinfo)
- TBD

this will be a living issue, i will upddate as we go through the changes

**Comment by damiannolan** [comment]
Some other notable things:
- [ ] Changes to simapp (root.go)
- [ ] Basic Manager removal
- [ ] AnteHandler consolidation
- [ ] Protobuf generation (updating of any opt for cosmos/gogo changes)

See: https://github.com/cosmos/cosmos-sdk/blob/main/UPGRADING.md#v052x

**Comment by gjermundgaraba** [comment]
Reopening to track remaining items

**Comment by gjermundgaraba** [comment]
Closing this as SDK 0.52 is not happening.
