### ISSUE TITLE
[EPIC] ICS 20 modifications for gas optimisations for Eureka

### ISSUE THREAD

**Issue by womensrights** [cosmos/ibc-go#7590]
## Summary

This issue will track all possible modifications that will enable cheaper, more gas optimised token transfers between Cosmos chains and Ethereum

## Problem Definition

ICS 20 is currently not optimised for performance within the EVM. The lower the gas cost for a completed token transfer, the better as end users will be paying less. 

## Use cases

Affordable token transfer between a Cosmos chain and Ethereum

## Proposal

Investigation of optimisations is ongoing, issues include: 
- supporting ABI encoding

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned
- [ ] Estimate provided

**Comment by gjermundgaraba** [comment]
We've done what we can for this release, so closing this for the initial release.
We can always revisit if we want to do more on this later.

**Comment by gjermundgaraba** [comment]
This issue was mistakenly reopened during some integration work, so closing again now.
