### ISSUE TITLE
Relayer Incentivization UI

### ISSUE THREAD

**Issue by AdityaSripal** [cosmos/ibc-go#871]
- [x] [Add gRPC/cli for incentivized packets on a certain channel](https://github.com/cosmos/ibc-go/issues/970) (gRPC: #983)
- [x] [Add gRPC/cli for counterparty address (registered relayer address)](https://github.com/cosmos/ibc-go/issues/1132) (gRPC and cli: #1224)
- [x] [Add gRPC/cli for fee enabled channels](https://github.com/cosmos/ibc-go/issues/857) (gRPC and cli: #1225 )
- [x] [Add cli for async incentivizing packet](https://github.com/cosmos/ibc-go/issues/963) (#965)
- [x] Add cli for incentivized packets (in combination with existing gRPCs) (#1229)

Nice to have:
- [ ] Add gRPC/cli for filtering incentivized packets by fees (minimum amount, by priority, etc)

This is a meta-issue for convenience. For implementers, please check off the tasks that you implement in PRs, or write up smaller issues that are subsets of this issue.

**Comment by crodriguezvega** [comment]
For alpha release (thus highest priority) we should implement first these 2:
- [ ] Add cli for async incentivizing packet
- [ ] Add gRPC/cli for counterparty address (registered relayer address)
